### PR TITLE
Nkot

### PR DESCRIPTION
**Pull request by Nazarkos22**
I`m confident, that the reason is very simple and ridiculous, but i can`t find it out yet) Please ADVISE SMTHG!!!
The main progect is "FLASH_test"
Int project "Kit_flash" Error with interrupts
 P.S. don`t pay attention on unflexible code in MAIN in both of projects, I simply tried to force it work)

### CODE REVIEW

**Comment by alexsuch** [comment]
@Nazarkos22 Could you send a screenshot of the error? Both projects build well on my side. And one more. What is functionality of your code? We were talking about copying of my code/ We need to have a meeting about this

**Comment by Nazarkos22** [comment]
@alexsuch There isn`t any error with building! When debug, my functions, called in main, are skipping in "FLASH" and error with "Kit_flash"
Now І can`t send a screenshot, because have no devise(ATSE has mine now for his homework)

**Comment by alexsuch** [comment]
@Nazarkos22 Is it works for now?

**Comment by Nazarkos22** [comment]
@alexsuch Sorry for no comments, will fix it

**Comment by Nazarkos22** [comment]
> @alexsuch Sorry for no comments, will fix it

fixed!

**Comment by Nazarkos22** [comment]
image
@alexsuch Cant fix this warning yet

**Comment by Nazarkos22** [comment]
@alexsuch 
Status: a problem is, that sensor scanning does not finish
            maybe It is from Creator or PSoC
            Will try to exlude Creator, and if it do not help, going to try other PSoc on Monday in office

**Pull request merged**
